Hot Fixes
fix(link): this.$attrs  may be undefined, due to this error in b-navbar-nav> b-nav-item

    [Vue warn]: Error in render function: "TypeError: Cannot read property 'tabindex' of undefined"
    TypeError: Cannot read property 'tabindex' of undefined